# Generated by Django 2.2.20 on 2022-01-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed_name', 'follower_id')},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followed_id',
        ),
    ]
